services:
  rabbitmq:
    extends:
      file: ./infra/docker-compose.yml
      service: rabbitmq

  postgres-order:
    extends:
      file: ./infra/docker-compose.yml
      service: postgres-order

  postgres-product:
    extends:
      file: ./infra/docker-compose.yml
      service: postgres-product

  order-service:
    extends:
      file: ./order-service/docker-compose.yml
      service: order-service
    depends_on:
      - rabbitmq
      - postgres-order

  product-service:
    extends:
      file: ./product-service/docker-compose.yml
      service: product-service
    depends_on:
      - rabbitmq
      - postgres-product

networks:
  microservices-net:
    name: microservices-net