services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: secret
    networks:
      - microservices-net

  postgres-order:
    extends:
      file: ./order-service/compose.yml
      service: postgres-order

  postgres-product:
    extends:
      file: ./product-service/compose.yml
      service: postgres-product

  order-service:
    extends:
      file: ./order-service/compose.yml
      service: order-service
    depends_on:
      - rabbitmq
      - postgres-order

  product-service:
    extends:
      file: ./product-service/compose.yml
      service: product-service
    depends_on:
      - rabbitmq
      - postgres-product

networks:
  microservices-net:
    name: microservices-net
