spring.application.name=order-service

# Db configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5433/order-db
spring.datasource.username=postgres
spring.datasource.password=*****

# JPA configuration
spring.jpa.show-sql=true

# RabbitMQ configuration
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=myuser
spring.rabbitmq.password=secret

